apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pingdom-statuspage-integration.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pingdom-statuspage-integration.name" . }}
    helm.sh/chart: {{ include "pingdom-statuspage-integration.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pingdom-statuspage-integration.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pingdom-statuspage-integration.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "pingdom-statuspage-integration.name" . }}
                  key: secret
            - name: STATUSPAGE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "pingdom-statuspage-integration.name" . }}
                  key: statuspageToken
            - name: MAX_RETRIES
              value: {{ default "2" .Values.config.maxRetries | quote }}
            - name: RETRY_INTERVAL
              value: {{ default "10" .Values.config.retryInterval | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}