apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pingdom-statuspage-integration.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "pingdom-statuspage-integration.name" . }}
    helm.sh/chart: {{ include "pingdom-statuspage-integration.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.config.secret | b64enc }}
  statuspageToken: {{ .Values.config.statuspageToken | b64enc }}